version: "2.1"

services:
  app:
    build: "."
    container_name: backend_grocery
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:mySecretPassword@db:5432/postgres?schema=public
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: postgresdb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mySecretPassword
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
